{{- if .Values.validator.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "hono-load-test.fullname" . }}-validator
  labels:
    {{- include "hono-load-test.labels" . | nindent 4 }}
    app.kubernetes.io/component: validator
spec:
  template:
    metadata:
      labels:
        {{- include "hono-load-test.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: validator
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "hono-load-test.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      restartPolicy: {{ .Values.validator.restartPolicy }}
      initContainers:
      - name: wait-for-registrar
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          echo "Waiting for registrar to complete..."
          while [ ! -f /shared-data/devices.json ]; do
            echo "Waiting for devices.json..."
            sleep 5
          done
          echo "Registrar completed, starting validator"
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
      containers:
      - name: validator
        image: {{ .Values.validator.image.repository | default .Values.image.repository }}:{{ .Values.validator.image.tag | default .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python", "/app/validator/main.py"]
        env:
        - name: SERVICE_MODE
          value: "validator"
        envFrom:
        - configMapRef:
            name: {{ include "hono-load-test.fullname" . }}-config
        volumeMounts:
        - name: shared-data
          mountPath: /shared-data
        - name: hono-config
          mountPath: /app/hono.env
          subPath: hono.env
        resources:
          {{- toYaml .Values.validator.resources | nindent 10 }}
      volumes:
      {{- if .Values.persistence.enabled }}
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ include "hono-load-test.pvcName" . }}
      {{- else }}
      - name: shared-data
        emptyDir: {}
      {{- end }}
      - name: hono-config
        configMap:
          name: {{ include "hono-load-test.fullname" . }}-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
